### ISSUE TITLE
Add docs for `integral-numbers` concept

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/haxe#215] opened 2022-04-22 10:12 UTC
The `integral-numbers` concept is listed in the `config.json`'s `concepts` key, but doesn't have its corresponding files in the `concepts/integral-numbers` directory.

**Comment by BNAndras** [comment] 2023-09-15 07:01
Caused by #199 which removed the `integral-numbers` concept files and fixed by #208 which dropped it from config.json

**Closed by BNAndras** 2023-09-15 07:01 UTC
