### ISSUE TITLE
Add docs for `indexers` concept

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/haxe#213] opened 2022-04-22 10:12 UTC
The `indexers` concept is listed in the `config.json`'s `concepts` key, but doesn't have its corresponding files in the `concepts/indexers` directory.

**Comment by BNAndras** [comment] 2023-09-15 07:05
Caused by #199 which removed the `indexers` concept files and fixed by #208 which dropped it from config.json

**Closed by BNAndras** 2023-09-15 07:05 UTC
